### PR TITLE
improve performance by not using spread operator

### PR DESCRIPTION
**Pull request by Lesiuk**
## Description

I swapped every usage of spread operator inside reduce to improve performance.

## Checklist

- [X] Changes are covered by tests if behavior has been changed or added
- [X] Tests have 100% coverage
- [x] If code changes were made, the version in `package.json` has been bumped (matching semver)
- [x] If code changes were made, the `yarn build` command has been run and to update the `cdn` directory

### CODE REVIEW

**Comment by rayepps** [comment]
Wow @Lesiuk thank you for doing this! So I can merge it
1. Bump the version in package.json
2. Run `yarn format`
3. Run `yarn build`
4. commit all the changes and push

**Comment by rayepps** [comment]
Looks like your behind the `master` branch by 1 commit and there are some conflicts

**Comment by Lesiuk** [comment]
@rayepps I resolved those issues.

**Review by rayepps — APPROVED** [review]

**Comment by rayepps** [comment]
There may be other perf issues we haven't seen/found yet but these changes resolve the current state of #78 🎉 Huge thanks to @Lesiuk ❤️

**Comment by rayepps** [comment]
This is published and available in `v10.3.2` 🚀

**Pull request merged**
