### PR TITLE
Add readonly types

### PR DESCRIPTION
**Pull request by aki77**
The following code results in a type error.

https://www.typescriptlang.org/play?jsx=0#code/JYWwDg9gTgLgBAbzgcyhArmOBfOAzNEOAcigEMATMgZwAtiAoBgYwgDtr49g64BeOAG0EDOHDZkQAUwBcJALJkoAG2BtiAGlFxqGKM1kkIBsuobYNibROlziAIRrVN23en2HiysgGspjCysxG08AFTR0GBcxNw87bz8AgF04GjhWDhgmDM58Hlp7AE8AZT0DfhQIsAAKbjpLPH4APnwAOliDAEo4IA

### CODE REVIEW

**Comment by rayepps** [comment]
Hey @aki77 thanks for bringing this up! I see the tests are passing so thats sweet 🍭  I love that 😍  

My first thought is that this is good, marking argument types as `readonly` is even more explicit to users that their values won't be modified.

I never use `as const`... not like I'm against it I've just never had the need. I know people who have, I've seen their code, and in many cases I've removed it 😬 I bring this up not to say I hate it but that I don't know much about it. Similarly, I don't know much about `readonly`.

Let me ask a probably dumb question, are there any downsides to consider?

**Comment by aki77** [comment]
Thanks for the reply.
`as const` was a simple example to define a `readonly` array.

I don't think there are any disadvantages.
You can continue to pass non-readonly arrays.

https://www.typescriptlang.org/play?jsx=0#code/KYDwDg9gTgLgBAYwgOwM7wOZQgVzHAXjgB4AVAPgAoBDKKagTwC44phqATFAGwblIDaAXQA0cDMBgBxbGBwBJDi0oBLGMAC2LUgEpC5OOigrkGPQQMBvAFBxWknFGRxa9BgDo2HHAmCUaCAhiaprmVrZ2iCjo4th4ioTikjIQcoqq6ho6EXZIaJhxYAAyKjFE1IECWLhgikJwAPwNcMI59jCOzpZw7r0VQS3V8RxCLAK97kPFpTDBmfUAvhELYpYLLqhwAErASFAcxEYmGGKCQuTZS9Z5MQBmpQAWiQI2dsjUGsAsAOQAsrTcEzfEQRVC4KC+H4QXzUZDfawrOCvODvT4-ABC1FQqGBoPBkLg3241AA1sB4YjkaivoTSHEYLi7GDHASiaTyQihNZrtF4PdUA90QwAMr44CJKaUfkPMS3fRwW7uZkQ4A6IA

**Comment by rayepps** [comment]
Ok, I talked to a friend and pulled your branch to play around with it and I'm very much sold 👍

**Review by rayepps — APPROVED** [review]

**Comment by aki77** [comment]
Thanks!

**Pull request merged**
