### PR TITLE
fixed the camal typo

### PR DESCRIPTION
**Pull request by danish-mehmood**
there was this typo in the code 'camal' when it shout be 'camel' i have fixed it 
and also working on docs to fix this

### CODE REVIEW

**Comment by rayepps** [comment]
Hey @danish-mehmood thanks so much for the PR! I'm a very bad speller so its great to get someone with that skill to help improve the codebase.

I pulled your branch and ran the tests and they're failing. This is kind of on me for not having a good contributing guide. You can run `yarn test` to run the test. They should pass and have 100% coverage.
Screen Shot 2022-08-26 at 7 36 07 PM

Also, can you add an alias in the index file and a comment that the old spelling is being deprecated? If we change the name I'll have to bump a major version. I'm trying to be a better open source maintainer and do that less 😬 In the next major version we can remove the old spelling.
```ts
export { 
  camel,
  camal: camel,
} from './string'
```

**Comment by danish-mehmood** [comment]
no problem i will do it

**Comment by rayepps** [comment]
Hey @danish-mehmood I'm gonna close this in favor of #58 just cus it's ready for merge.

**Comment by danish-mehmood** [comment]
@rayepps  m so sorry , i have been very ill for the past week , couldn't see any progress on my github , is this issue still needs to be resolved or not ?

**Comment by rayepps** [comment]
Hey @danish-mehmood no worries, I was away for a bit myself. I hope all is well with you! This issue is all taken care of 😃

**Pull request closed without merging**
