### PR TITLE
feat!: drop support for node 12

### LINKED ISSUE #109: Drop support for node v12
Based on chat with @matteosacchetto in #108 we'll drop support for node 12 after node v18 becomes LTS on `2022-10-25`. This will be a major version bump to `9.0.0`.

Screen Shot 2022-10-18 at 9 35 28 AM

See Node release calendar [here](https://github.com/nodejs/Release).

### PR DESCRIPTION
**Pull request by matteosacchetto**
## Description
Drop support for node 12 and support node 14, 16 and 18 (all current LTS under maintenance) 

## Checklist
- [x] Changes are covered by tests if behavior has been changed or added
- [x] Tests have 100% coverage
- [x] The version in `package.json` has been bumped according to the changes made and standard semantic versioning rules

## Resolves
Resolves #109

### CODE REVIEW

**Review by rayepps — APPROVED** [review]
This is awesome @matteosacchetto 👍 thank you!

**Comment by rayepps** [comment]
This is huge 🎉 I don't see any reason to not merge it so... I'm gonna do it. Here comes `v9.0.0` 🚀

**Comment by rayepps** [comment]
> In case the build step fails it should be as easy as setting the `useEsbuild` flag to `false` If the build step fails feel free to hit me up and I will do all the required changes to obtain the same output using `tsc` instead of `esbuild`

I pulled your branch and ran the build on node 14, 16, and 18 with success. I feel confident it's going to work 👍 if there are any odd issues in ci we can take care of them 😃

**Comment by matteosacchetto** [comment]
Yeah, I did the same test to make sure that It was building for node 14, 16 and 18.
This was just a reminder in case of future issues

In case of future issues feel free to hit me up about it! 😉

**Pull request merged**
