### PR TITLE
Improve the type coverage of clone function

### PR DESCRIPTION
**Pull request by mertdy**
- The current clone function throws an error when the parameter is 'undefined' or 'null', even though 'null' is considered as 'object' by TS.

- Since the current clone function creates an empty object and assign the old props, the new object is actually not an copy of the given object when the given object is a class instance. It loses the parameter's class definition.

- The current clone function can only clone objects and arrays but not primitive types or functions. By adding a primitive check, its type coverage can be increased.

### CODE REVIEW

**Comment by rayepps** [comment]
Hey @mertdy thank you for taking the time to make this PR! Apologies it's taken so long to address it. I just fixed all the merge conflicts and labeled it for release.

Since you created it we've added some automation around formatting, if you could run `yarn format` and commit the changes so the [format ci check](https://github.com/rayepps/radash/actions/runs/3352686249/jobs/5554994582) can pass I'll merge 🚀

**Comment by rayepps** [comment]
Hey @mertdy  I'd really like to get this change in. It's just out of date on some process items we've added since you opened the PR. If you want to update it:
- rebase with the `master` branch
- bump the version in package.json
- run `yarn format`
- run `yarn build`
- push 🚀 

I know open source probably isn't the highest priority so I understand if you can't, I just don't want to take your well-earned contribution. If I don't hear back soon I'll close this and open a new PR to push through.

**Comment by mertdy** [comment]
Hey @rayepps thanks for your response. 
I think this library is worth to contribute since it is a nice idea to replace the lodash with a better alternative. I would be really happy even if I can provide a bit help.

It is not about open source. However, after an 2 months old uncommented PR, things start to lose their priority. I don't even remember what I did.

November is being a busy month but I am gonna update the PR at the first chance 😇👍🏻.

**Comment by mertdy** [comment]
Hi @rayepps,
The PR is up-to-date. fyi

**Pull request merged**
