### PR TITLE
feat(string): add `kebab` function

### PR DESCRIPTION
**Pull request by Nickersoft**
## Description

You can tell me what you think of this – I figured it'd be easier to just open a PR than an issue. I was surprised to see Radash doesn't have a `kebab` function to complement its `snake` and `camel` functions. This PR adds it. In my own code, I originally was getting around this by doing `snake("myString").replace("_", "-")`, and _almost_ just had this be the implementation in this PR, but thought it would be better to:

1. Not have the additional dependency on the `snake` method
2. Not have the addition operational overhead of needing to run `snake`, _then_ an additional `replace` on top of it

I personally think a lot of the logic shared between `camel`, `snake`, and `kebab` could be extracted to its own helper method, but Radash doesn't seem to have any internal methods like that, so I figured I'd leave it to your discretion.

## Checklist

- [x] Changes are covered by tests if behavior has been changed or added
- [x] Tests have 100% coverage
- [x] If code changes were made, the version in `package.json` has been bumped (matching semver)
- [x] If code changes were made, the `yarn build` command has been run and to update the `cdn` directory

### CODE REVIEW

**Comment by rayepps** [comment]
What's the difference between `kebab` and `dash`?

**Comment by rayepps** [comment]
It looks like you're `kebab` function is identical to the current `dash` function. So clearly I named the function poorly 😞

**Comment by Nickersoft** [comment]
@rayepps Holy lmao. Yeah I guess that's on me – opening an issue first would have been valuable here lol. Damn. 

Guess I'll use that then 😅  This style of naming is [formally called kebab case though](https://en.wiktionary.org/wiki/kebab_case). 

Good thing this PR didn't take long!

**Comment by rayepps** [comment]
Maybe we should add an export for it as kebab and add a page to the docs site as kebab so others can find it easily?

**Comment by Nickersoft** [comment]
Honestly, I'd be in favor of just renaming the function 😅 Not to introduce yet _another_ breaking change to your repo haha...

I think for now though it's fine – it's just on me for not reading the docs closer. I think having a function alias would just complicate things.

**Comment by wouterkroes** [comment]
First of all, thanks for this great (looking) library! 
I am investigating migrating from Lodash to Radash.

Maybe it is possible to add the word kebab in the description of the method? Or as tag / meta data somewhere? 
Coming from Lodash kebab is the word that you look for in the Radash docs.

I think this is the correct term for and not dash (https://en.wiktionary.org/wiki/kebab_case#English)

Or maybe accept the breaking change, to be consistent with the rest of the web?

Many thanks

**Pull request closed without merging**
